import { VideoProject } from "@/types/videos";

// Instagram reels data (keeps same shape as VideoProject for easy reuse)
export const allReels: VideoProject[] = [
 {
    id: "reel-1",
    video_title: "Event Organising Company Reel",
    video_description: "A event reel designed with creative angles, smooth transitions, and unique concept. I handled both the shoot and edit.",
    tags: ["Event Organising", "DRIP TRIP", "Reel"],
    cover_image: "/project-images/drip.PNG",
    publish_date: "2024-06-01",
    client_name: "Company",
    client_image: "/companies/drip.PNG",
    client_feedback: "",
    video_link: "https://drive.google.com/drive/folders/1HgAg2NbFzMzozn1HJP3CrReixo4CrihI",
    project_images: [],
    category: ["Promo", "Reel"],
    duration: "0:30",
    software_used: ["Davinci Resolve"],
  },
  {
    id: "reel-2",
    video_title: "High reach for client",
    video_description: "56M+ reach generated through my edits. I also provided content ideas and upload strategy to the client.",
    tags: ["Avanya", "Viral", "Reel"],
    cover_image: "/project-images/avanya.PNG",
    publish_date: "2024-06-01",
    client_name: "Client",
    client_image: "/companies/impel-it.png",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/DLmwVKLSCv8/?igsh=cnRid205OWozYm5p",
    project_images: [],
    category: ["Promo", "Reel"],
    duration: "0:30",
    software_used: ["Davinci Resolve"],
  },

  {
    id: "reel-3",
    video_title: "Mohit Chauhan - Epoque 2025 Reel",
    video_description: "Edited reel of Mohit Chauhan's performance during Epoque 2025 college fest — captured his visit and highlights from the event.",
    tags: ["Mohit Chauhan", "Epoque2025", "Reel"],
    cover_image: "/project-images/mohit_chauhan.webp",
    publish_date: "2024-06-01",
    client_name: "fest",
    client_image: "/companies/KIET.jpg",
    client_feedback: "",
    video_link: " https://www.instagram.com/reel/DHlS1pUqGYV/",
    project_images: [],
    category: ["Promo", "Reel"],
    duration: "0:30",
    software_used: ["Davinci Resolve"],
  },

];
