import { VideoProject } from "@/types/videos";

// Instagram reels data (keeps same shape as VideoProject for easy reuse)
export const allReels: VideoProject[] = [
  {
    id: "reel-1",
    video_title: "AVANYA BRAND INTRO ANIMATION (Reel)",
    video_description: "Short brand intro animation showcased as an Instagram Reel.",
    tags: ["Brand", "Animation", "Reel"],
    cover_image: "/project-images/one.png",
    publish_date: "2024-04-12",
    client_name: "Stack Learner",
    client_image: "/companies/sl-logo.png",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/DP1OvbPkzHc/?igsh=emRiOWVjY3hzNncz",
    project_images: [],
    category: ["Motion Graphics", "Reel"],
    duration: "0:22",
    software_used: ["After Effects"],
  },

  {
    id: "reel-2",
    video_title: "Dynamic Promo Reel",
    video_description: "A fast-paced promo reel showcased on Instagram.",
    tags: ["Promo", "Reel"],
    cover_image: "/project-images/two.png",
    publish_date: "2024-06-01",
    client_name: "Client",
    client_image: "/companies/impel-it.png",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/DQG-U7gkxVy/?wa_logging_event=video_play_open",
    project_images: [],
    category: ["Promo", "Reel"],
    duration: "0:30",
    software_used: ["Davinci Resolve"],
  },
    {
    id: "reel-3",
    video_title: "NEW ONE",
    video_description: "A fast-paced promo reel showcased on Instagram.",
    tags: ["Promo", "Reel"],
    cover_image: "/project-images/two.png",
    publish_date: "2024-06-01",
    client_name: "Client",
    client_image: "/companies/impel-it.png",
    client_feedback: "",
    video_link: "https://www.instagram.com/reel/DLmwVKLSCv8/?igsh=cnRid205OWozYm5p",
    project_images: [],
    category: ["Promo", "Reel"],
    duration: "0:30",
    software_used: ["Davinci Resolve"],
  },
 
   {
    id: "reel-4",
    video_title: "NEW ONE",
    video_description: "A fast-paced promo reel showcased on Instagram.",
    tags: ["Promo", "Reel"],
    cover_image: "/project-images/mohit_chauhan.webp",
    publish_date: "2024-06-01",
    client_name: "Client",
    client_image: "/companies/impel-it.png",
    client_feedback: "",
    video_link: " https://www.instagram.com/reel/DHlS1pUqGYV/",
    project_images: [],
    category: ["Promo", "Reel"],
    duration: "0:30",
    software_used: ["Davinci Resolve"],
  },

];
